#
# Black formatter config
#
[tool.black]
line-length = 88                     # PEP8, or 79 is accepted
target-version = ['py38', 'py39']   # supported python versions
skip-string-normalization = false   # false: enforce double quotes, true: leave all quotes as they are
include = '\.pyi?$'                  # apply to python only
exclude = '''
(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv[^/]*
  | _build
  | buck-out
  | build
  | dist
)
'''                                 # Exclude common build and VCS directories

#
# MyPy static typing config
#
[tool.mypy]
python_version = "3.13"
strict = false  # after more experience with python typing be sure to set thist true!
ignore_missing_imports = true
check_untyped_defs = false
disallow_untyped_defs = false
warn_unused_ignores = true
warn_return_any = true
